/* =============================================================================
   ATTICO PANORAMICO — TESTI DEL SITO (IT / EN / DE / FR)

   Per correggere o aggiungere un testo si modifica SOLO questo file,
   poi si rigenerano le pagine con:  node genera-pagine.js
   Ogni lingua ha le stesse chiavi; se una chiave manca, si usa l'italiano.
   Titolo, descrizione e dati per Google stanno invece in seo/it.html, en, de, fr
   (meta_title e meta_desc qui sotto non sono più usati).
   ============================================================================= */

/* ---------- Dati fissi (uguali in tutte le lingue) ---------- */
var DATI = {
  whatsapp: '393880775449',
  indirizzo: 'Via Cristoforo Colombo, 7 — 98057 Milazzo (ME), Sicilia',
  mappa: 'https://maps.google.com/?q=Via+Cristoforo+Colombo+7+Milazzo+ME',
  percorso: 'https://www.google.com/maps/dir/?api=1&destination=38.22509,15.24127',
  guidaCasa: 'https://pxh2407.github.io/panoramicpenthouse_info/',
  cin: 'IT083049C2FNPHRA9D',
  cir: '19083049C206347',
  lat: 38.22509,
  lon: 15.24127,
  ospitiMax: 8
};

/* ---------- Foto della galleria ----------
   cat: esterni | soggiorno | camere | servizi
   forma: grande | larga | alta | (vuoto = normale)                          */
var FOTO = [
  { file: 'DSC5134-scaled-960x800_c.webp', cat: 'esterni',   forma: 'grande',
    it: 'La terrazza panoramica sul mare', en: 'The panoramic terrace overlooking the sea', de: 'Die Panoramaterrasse mit Meerblick', fr: 'La terrasse panoramique sur la mer' },
  { file: 'DSC5102-scaled-960x800_c.webp', cat: 'soggiorno', forma: 'larga',
    it: 'Soggiorno con zona pranzo', en: 'Living room with dining area', de: 'Wohnzimmer mit Essbereich', fr: 'Séjour avec coin repas' },
  { file: 'DSC4978-scaled-960x800_c.webp', cat: 'camere',    forma: 'alta',
    it: 'Camera matrimoniale con letto in ottone', en: 'Double bedroom with brass bed', de: 'Doppelzimmer mit Messingbett', fr: 'Chambre double avec lit en laiton' },
  { file: 'DSC4989-scaled-960x800_c.webp', cat: 'soggiorno', forma: '',
    it: 'Home cinema con videoproiettore', en: 'Home cinema with projector', de: 'Heimkino mit Beamer', fr: 'Home cinéma avec vidéoprojecteur' },
  { file: 'DSC5148-scaled-960x800_c.webp', cat: 'esterni',   forma: 'alta',
    it: 'Angolo relax con sdraio', en: 'Relaxing corner with loungers', de: 'Ruheecke mit Liegestühlen', fr: 'Coin détente avec chaises longues' },
  { file: 'DSC5091-scaled-960x800_c.webp', cat: 'soggiorno', forma: '',
    it: 'Il salotto e lo schermo del cinema', en: 'The lounge and the cinema screen', de: 'Die Lounge mit Kinoleinwand', fr: 'Le salon et l\'écran de cinéma' },
  { file: 'DSC5058-scaled-960x800_c.webp', cat: 'camere',    forma: 'larga',
    it: 'Camera matrimoniale luminosa', en: 'Bright double bedroom', de: 'Helles Doppelzimmer', fr: 'Chambre double lumineuse' },
  { file: 'DSC4995-scaled-960x800_c.webp', cat: 'servizi',   forma: 'alta',
    it: 'Cucina attrezzata', en: 'Equipped kitchen', de: 'Ausgestattete Küche', fr: 'Cuisine équipée' },
  { file: 'DSC4966-scaled-960x800_c.webp', cat: 'camere',    forma: '',
    it: 'Camera con due letti singoli', en: 'Twin bedroom', de: 'Zweibettzimmer', fr: 'Chambre à deux lits' },
  { file: 'DSC5109-scaled-960x800_c.webp', cat: 'servizi',   forma: 'larga',
    it: 'Bagno', en: 'Bathroom', de: 'Badezimmer', fr: 'Salle de bain' },
  { file: 'DSC5029-scaled-960x800_c.webp', cat: 'servizi',   forma: '',
    it: 'Box doccia', en: 'Shower', de: 'Dusche', fr: 'Douche' }
];

/* ---------- Isole Eolie (posizione reale, per la mappa illustrata) ---------- */
var ISOLE = [
  { nome: 'Stromboli', lat: 38.793, lon: 15.213, kmq: 12.6 },
  { nome: 'Panarea',   lat: 38.637, lon: 15.073, kmq: 3.4 },
  { nome: 'Salina',    lat: 38.560, lon: 14.840, kmq: 26.8 },
  { nome: 'Lipari',    lat: 38.480, lon: 14.945, kmq: 37.6 },
  { nome: 'Vulcano',   lat: 38.395, lon: 14.965, kmq: 21.0 },
  { nome: 'Filicudi',  lat: 38.570, lon: 14.565, kmq: 9.5 },
  { nome: 'Alicudi',   lat: 38.543, lon: 14.353, kmq: 5.2 }
];

/* =============================================================================
   TESTI PER LINGUA
   ============================================================================= */
var TESTI = {

/* ============================ ITALIANO ============================ */
it: {
  meta_title: 'Attico Panoramico Milazzo – Casa Vacanze Vista Mare | Sicilia',
  meta_desc: 'Casa vacanze nel centro storico di Milazzo con terrazza panoramica vista mare, garage privato, home cinema e WiFi. Fino a 8 ospiti, 82 recensioni 5 stelle.',
  skip: 'Salta al contenuto principale',
  tagline: 'La tua oasi a Milazzo!',

  nav_apartment: 'L\'Appartamento',
  nav_gallery: 'Galleria',
  nav_amenities: 'Servizi',
  nav_location: 'Dove siamo',
  nav_discover: 'Scopri Milazzo',
  nav_availability: 'Disponibilità',
  nav_reviews: 'Recensioni',
  nav_faq: 'Domande',
  nav_book: 'Prenota',
  menu_open: 'Apri il menu',
  menu_close: 'Chiudi il menu',

  hero_eyebrow: 'Milazzo · Sicilia',
  hero_sub: 'Vista mare nel centro storico di Milazzo',
  hero_desc: 'Eleganza, comfort e panorami mozzafiato nel cuore di Milazzo. Terrazza privata, garage incluso, home cinema e il porto per le Isole Eolie a 15 minuti a piedi.',
  hero_cta_dates: 'Verifica le date',
  hero_cta_wa: 'Scrivici su WhatsApp',
  hero_rating_label: '82 recensioni',
  hero_rating_source: 'Airbnb',
  hero_alt: 'La terrazza panoramica dell\'Attico con vista sul mare di Milazzo',
  img_alt: 'Attico Panoramico, casa vacanze a Milazzo',
  about_img_alt: 'Soggiorno con zona pranzo dell\'Attico Panoramico, casa vacanze nel centro storico di Milazzo',
  about_inset_alt: 'Home cinema con videoproiettore nella casa vacanze Attico Panoramico a Milazzo',

  live_time: 'Ora a Milazzo',
  live_weather: 'Il cielo',
  live_sea: 'Il mare',
  live_sunset: 'Tramonto',
  live_sunset_tomorrow: 'Tramonto domani',
  live_in: 'tra',
  w_clear: 'Sereno', w_partly: 'Poco nuvoloso', w_cloudy: 'Nuvoloso', w_fog: 'Nebbia',
  w_drizzle: 'Pioviggine', w_rain: 'Pioggia', w_snow: 'Neve', w_storm: 'Temporale',

  feat_guests: 'Fino a 8 ospiti',
  feat_guests_sub: 'Appartamento indipendente',
  feat_sea: 'Vista Mare',
  feat_sea_sub: 'Terrazza panoramica',
  feat_garage: 'Garage privato',
  feat_garage_sub: 'Posto auto incluso',
  feat_cinema: 'Home Cinema',
  feat_cinema_sub: 'Videoproiettore HD',
  feat_library: 'Biblioteca',
  feat_library_sub: 'Oltre 300 volumi',
  feat_stars: '5 stelle · 82 recensioni',
  feat_stars_sub: 'Su Airbnb',

  about_label: 'L\'appartamento',
  about_title: 'Lusso e comfort<br>nel cuore di Milazzo',
  about_desc: 'Soggiorna in un elegante appartamento indipendente che offre il massimo del relax e del benessere. Ogni dettaglio è stato curato per regalarti un\'esperienza unica e indimenticabile, a pochi passi da ristoranti, bar, spiagge e dal porto per le Isole Eolie.',
  stat_guests: 'Ospiti massimo',
  stat_rating: 'Valutazione ospiti',
  stat_reviews: 'Recensioni su Airbnb',
  stat_books: 'Libri in biblioteca',

  gallery_label: 'Fotografie',
  gallery_title: 'Scorci dell\'appartamento',
  gallery_desc: 'Spazi luminosi, arredi curati e panorami che lasciano senza fiato',
  filter_all: 'Tutte',
  filter_esterni: 'Terrazza',
  filter_soggiorno: 'Soggiorno',
  filter_camere: 'Camere',
  filter_servizi: 'Cucina e bagno',
  gallery_open: 'Apri la foto',
  lb_close: 'Chiudi',
  lb_prev: 'Foto precedente',
  lb_next: 'Foto successiva',

  amenities_label: 'Dotazioni',
  amenities_title: 'Tutto ciò che ti serve',
  amenities_desc: 'L\'appartamento è stato allestito con cura per garantirti un soggiorno confortevole e senza pensieri',
  amen_conn_title: 'Connettività',
  amen_conn_1: 'WiFi gratuito dual-band (5G e 2.4G)',
  amen_conn_2: 'TV in ogni stanza',
  amen_conn_3: 'Stazione di ricarica USB (6 porte)',
  amen_conn_4: 'Videoproiettore home cinema',
  amen_kitchen_title: 'Cucina',
  amen_kit_1: 'Cucina completamente attrezzata',
  amen_kit_2: 'Forno elettrico multi-programma',
  amen_kit_4: 'Frigorifero, stoviglie e utensili',
  amen_climate_title: 'Clima e Comfort',
  amen_cli_1: 'Climatizzatori in ogni ambiente',
  amen_cli_2: 'Riscaldamento con cronotermostato',
  amen_cli_3: 'Avvolgibili motorizzati',
  amen_cli_4: 'Tenda oscurante camera',
  amen_parking_title: 'Parcheggio e Accesso',
  amen_park_1: 'Garage privato incluso',
  amen_park_2: 'Accesso con telecomando',
  amen_park_3: 'Ascensore in palazzo',
  amen_park_4: 'Stazione ricarica EV a 200m',
  amen_leisure_title: 'Svago e Cultura',
  amen_lei_1: 'Biblioteca con 300+ volumi',
  amen_lei_2: 'Home cinema con videoproiettore',
  amen_lei_3: 'Terrazza panoramica arredata',
  amen_lei_4: 'Veranda coperta con vista mare',
  amen_safety_title: 'Sicurezza',
  amen_saf_1: 'Rilevatore di fumo e CO',
  amen_saf_2: 'Rilevatore gas con elettrovalvola',
  amen_saf_3: 'Estintore in veranda',
  amen_saf_4: 'Kit pronto soccorso',

  loc_label: 'Dove siamo',
  loc_title: 'Nel centro di Milazzo,<br>a 15 minuti dal porto',
  loc_desc: 'Via Cristoforo Colombo, 7 — a pochi passi da ristoranti, bar, supermercati, spiagge e dal porto per le Isole Eolie.',
  walk_title: 'A piedi dall\'Attico',
  walk_conad: 'Supermercato Conad',
  walk_beach: 'Spiaggia di Ponente',
  walk_medical: 'Guardia Medica 24/7',
  walk_castle: 'Castello e Cittadella',
  walk_port: 'Porto per le Isole Eolie',
  walk_min: 'min a piedi',
  walk_m: 'metri',
  loc_beaches: 'Spiagge',
  loc_beaches_desc: 'Spiaggia di Ponente e Croce di Mare a pochi minuti a piedi',
  loc_restaurants: 'Ristoranti e Bar',
  loc_restaurants_desc: 'La Campagnola, Adagio-Adagio, Macchianera — tutti nelle vicinanze',
  map_open: 'Apri in Google Maps',
  map_route: 'Indicazioni stradali',
  map_title: 'Posizione dell\'Attico Panoramico su Google Maps – Via Cristoforo Colombo 7, Milazzo',

  disc_label: 'Scopri Milazzo',
  guide_label: 'Le nostre guide di viaggio',
  disc_title: 'Una destinazione tutta da vivere',
  disc_desc: 'Milazzo non è solo un punto di partenza per le Isole Eolie: è una città ricca di storia, spiagge e panorami unici, tutta da esplorare a piedi dal nostro appartamento.',
  disc_castle_title: 'Castello e Cittadella',
  disc_castle_desc: 'La cittadella fortificata più grande della Sicilia, oltre 7 ettari di storia. All\'interno il Duomo Antico (1608) e il <strong>MuMa — Museo del Mare</strong>. A 10 minuti a piedi dall\'appartamento.',
  disc_beach_title: 'Spiagge e Capo Milazzo',
  disc_beach_desc: '<strong>Spiaggia di Ponente</strong> a 5 minuti a piedi, Baia del Tono e la spettacolare <strong>Piscina di Venere</strong> — piscina naturale sulla punta estrema di Capo Milazzo, un promontorio di 8 km nel Tirreno.',
  disc_eolie_title: 'Isole Eolie',
  disc_eolie_desc: 'Il porto dista <strong>15 minuti a piedi</strong>. Aliscafi e traghetti collegano tutte e 7 le isole: Lipari, Vulcano, Salina, Stromboli, Panarea, Filicudi e Alicudi. Ideale per escursioni giornaliere.',
  disc_food_title: 'Gastronomia locale',
  disc_food_desc: 'Pesce fresco, arancini, granite siciliane e vini dell\'Etna. A pochi passi trovi La Campagnola, Macchianera e molti altri ristoranti tipici. L\'isola pedonale è il cuore della vita serale.',
  disc_how_title: 'Come arrivare',
  disc_how_desc: 'Da <strong>Catania (CTA)</strong>: 1h40 via A18+A20. Da <strong>Palermo (PMO)</strong>: 2h15 via A20. Da <strong>Messina</strong>: 35 min via A20. Stazione ferroviaria Milazzo sulla linea Messina–Palermo.',
  disc_history_title: 'Storia e Cultura',
  disc_history_desc: 'Fondata dai Greci nel 716 a.C., teatro della prima vittoria navale di Roma (260 a.C.) e della battaglia di Garibaldi (1860). Il Santuario di San Francesco di Paola è l\'unico in Sicilia dedicato al santo.',
  eolie_caption: 'Le sette isole, dal porto di Milazzo',
  eolie_sicily: 'Sicilia',
  eolie_sea: 'Mar Tirreno',

  avail_label: 'Calendario',
  avail_title: 'Verifica la disponibilità',
  avail_desc: 'Scegli la data di arrivo e di partenza: ti prepariamo noi il messaggio WhatsApp, devi solo inviarlo.',
  avail_free: 'Disponibile',
  avail_busy: 'Prenotato',
  avail_mine: 'Le tue date',
  avail_checkin: 'Arrivo',
  avail_checkout: 'Partenza',
  avail_guests: 'Ospiti',
  avail_night: 'notte',
  avail_nights: 'notti',
  avail_pick1: 'Tocca un giorno libero nel calendario, oppure qui sotto su «Arrivo»',
  avail_choose: 'Scegli',
  avail_pick2: 'Ora scegli il giorno di partenza',
  avail_ready: 'Date scelte: invia la richiesta su WhatsApp',
  avail_conflict: 'Alcune notti sono già prenotate: prova altre date.',
  avail_order: 'La partenza deve essere dopo l\'arrivo.',
  avail_reset: 'Cancella le date',
  avail_send: 'Invia su WhatsApp',
  avail_less: 'Un ospite in meno',
  avail_more: 'Un ospite in più',
  avail_prev: 'Mesi precedenti',
  avail_next: 'Mesi successivi',
  avail_loading: 'Caricamento disponibilità…',
  avail_error: 'Calendario non disponibile in questo momento: scegli comunque le date, te le confermiamo su WhatsApp.',
  avail_updated: 'Aggiornato:',
  cal_months: 'Gennaio,Febbraio,Marzo,Aprile,Maggio,Giugno,Luglio,Agosto,Settembre,Ottobre,Novembre,Dicembre',
  cal_days: 'Lun,Mar,Mer,Gio,Ven,Sab,Dom',

  msg_generic: 'Buongiorno! Vorrei informazioni sull\'Attico Panoramico di Milazzo.',
  msg_generic_dates: 'Buongiorno! Vorrei informazioni sull\'Attico Panoramico di Milazzo, con arrivo il {da} e partenza il {a}.',
  msg_dates: 'Buongiorno! Vorrei sapere se l\'Attico Panoramico è disponibile dal {da} al {a} ({notti}) per {ospiti}. Grazie!',
  msg_guest: 'ospite',
  msg_guests: 'ospiti',

  rev_label: 'Recensioni',
  rev_title: 'Le valutazioni dei nostri ospiti',
  rev_subtitle: '82 recensioni su Airbnb, valutazione 5,0',
  rev_count: 'Basato su 82 recensioni Airbnb',
  rev_source: 'Voti verificabili su ogni portale',
  rev_v_airbnb: '5,0',
  rev_v_booking: '9,8',
  rev_v_vrbo: '9,6',
  rev_n_airbnb: '82 recensioni',
  rev_n_booking: '22 recensioni',
  rev_n_vrbo: '5 recensioni',
  rev_badge_airbnb: 'Amato dagli ospiti',
  rev_badge_booking: 'Eccezionale',
  rev_badge_vrbo: 'Eccezionale',
  rev_leggi: 'Leggi le recensioni',

  faq_label: 'Domande frequenti',
  faq_title: 'Tutto quello che vuoi sapere',
  faq: [
    ['Dove si trova l\'Attico Panoramico di Milazzo?', 'L\'appartamento si trova in Via Cristoforo Colombo 7, nel centro storico di Milazzo (ME), Sicilia. È a pochi passi da ristoranti, bar, supermercati, spiagge e dal porto per le Isole Eolie.'],
    ['Quanti ospiti può ospitare l\'attico?', 'L\'appartamento può accogliere fino a 8 ospiti. Dispone di 3 camere da letto (due matrimoniali e una con due letti singoli), un divano letto matrimoniale nel salone, 2 bagni, cucina attrezzata e terrazza panoramica.'],
    ['È incluso il parcheggio?', 'Sì, l\'appartamento include un garage privato con accesso tramite telecomando, senza costi aggiuntivi.'],
    ['Qual è la valutazione dell\'appartamento?', 'L\'Attico Panoramico ha una valutazione di 5,0 su 5 su Airbnb, con 82 recensioni degli ospiti. Su Booking.com ha 9,8 su 10 (22 recensioni) e su Vrbo 9,6 su 10 (5 recensioni).'],
    ['Come contattare il proprietario per prenotare?', 'Scrivici su WhatsApp al +39 388 077 5449: è il modo più rapido per informazioni, disponibilità e prenotazioni.'],
    ['Cosa c\'è da vedere a Milazzo?', 'Milazzo offre il Castello e Cittadella fortificata (la più grande della Sicilia, oltre 7 ettari), Capo Milazzo con la Piscina di Venere, le spiagge di Ponente e Baia del Tono, il centro storico con isola pedonale, il Santuario di San Francesco di Paola e il MuMa — Museo del Mare.'],
    ['Come si raggiungono le Isole Eolie da Milazzo?', 'Il porto di Milazzo dista 15 minuti a piedi dall\'appartamento. Aliscafi e traghetti collegano tutte e 7 le isole Eolie (Lipari, Vulcano, Salina, Stromboli, Panarea, Filicudi, Alicudi), ideali per escursioni giornaliere.'],
    ['Come si arriva a Milazzo?', 'Da Catania Fontanarossa (CTA): 1h40 via autostrada A18+A20. Da Palermo Falcone-Borsellino (PMO): 2h15 via A20. Da Messina: 35 minuti via A20. Milazzo ha anche una stazione ferroviaria sulla linea Messina–Palermo.']
  ],

  cta_label: 'Prenota il tuo soggiorno',
  cta_title: 'Pronto per<br>un\'esperienza indimenticabile?',
  cta_desc: 'Contattaci direttamente per informazioni, disponibilità e tariffe: ti rispondiamo su WhatsApp.',
  cta_wa: 'Scrivici su WhatsApp',

  footer_desc: 'Elegante casa vacanze nel centro storico di Milazzo, con terrazza panoramica e vista mare.',
  footer_links_title: 'Link Rapidi',
  footer_contacts_title: 'Contatti',
  footer_rights: 'Tutti i diritti riservati',
  footer_guide: 'Guida Casa',
  bar_wa: 'WhatsApp'
},

/* ============================ ENGLISH ============================ */
en: {
  meta_title: 'Attico Panoramico Milazzo – Sea View Holiday Home | Sicily',
  meta_desc: 'Holiday home in the historic centre of Milazzo with a panoramic sea-view terrace, private garage, home cinema and WiFi. Up to 8 guests, 82 five-star reviews.',
  skip: 'Skip to main content',
  tagline: 'Your oasis in Milazzo!',

  nav_apartment: 'The Apartment',
  nav_gallery: 'Gallery',
  nav_amenities: 'Amenities',
  nav_location: 'Location',
  nav_discover: 'Discover Milazzo',
  nav_availability: 'Availability',
  nav_reviews: 'Reviews',
  nav_faq: 'FAQ',
  nav_book: 'Book',
  menu_open: 'Open menu',
  menu_close: 'Close menu',

  hero_eyebrow: 'Milazzo · Sicily',
  hero_sub: 'Sea view in Milazzo\'s historic centre',
  hero_desc: 'Elegance, comfort and breathtaking panoramas in the heart of Milazzo. Private terrace, garage included, home cinema and the Aeolian Islands ferry port a 15-minute walk away.',
  hero_cta_dates: 'Check dates',
  hero_cta_wa: 'Write us on WhatsApp',
  hero_rating_label: '82 reviews',
  hero_rating_source: 'Airbnb',
  hero_alt: 'The Attico\'s panoramic terrace overlooking the sea of Milazzo',
  img_alt: 'Attico Panoramico holiday apartment in Milazzo, Sicily',
  about_img_alt: 'Living room with dining area at the Attico Panoramico holiday apartment in Milazzo',
  about_inset_alt: 'Home cinema with projector at the Attico Panoramico, Milazzo',

  live_time: 'Now in Milazzo',
  live_weather: 'The sky',
  live_sea: 'The sea',
  live_sunset: 'Sunset',
  live_sunset_tomorrow: 'Sunset tomorrow',
  live_in: 'in',
  w_clear: 'Clear', w_partly: 'Partly cloudy', w_cloudy: 'Cloudy', w_fog: 'Fog',
  w_drizzle: 'Drizzle', w_rain: 'Rain', w_snow: 'Snow', w_storm: 'Thunderstorm',

  feat_guests: 'Up to 8 guests',
  feat_guests_sub: 'Independent apartment',
  feat_sea: 'Sea View',
  feat_sea_sub: 'Panoramic terrace',
  feat_garage: 'Private garage',
  feat_garage_sub: 'Parking included',
  feat_cinema: 'Home Cinema',
  feat_cinema_sub: 'HD Projector',
  feat_library: 'Library',
  feat_library_sub: 'Over 300 books',
  feat_stars: '5 stars · 82 reviews',
  feat_stars_sub: 'On Airbnb',

  about_label: 'The Apartment',
  about_title: 'Luxury and comfort<br>in the heart of Milazzo',
  about_desc: 'Stay in an elegant independent penthouse apartment offering the ultimate in relaxation and well-being. Every detail has been curated to give you a unique and unforgettable experience, just steps from restaurants, bars, beaches and the port for the Aeolian Islands.',
  stat_guests: 'Max guests',
  stat_rating: 'Guest rating',
  stat_reviews: 'Airbnb reviews',
  stat_books: 'Books in library',

  gallery_label: 'Photographs',
  gallery_title: 'Views of the apartment',
  gallery_desc: 'Bright spaces, refined furnishings and views that take your breath away',
  filter_all: 'All',
  filter_esterni: 'Terrace',
  filter_soggiorno: 'Living room',
  filter_camere: 'Bedrooms',
  filter_servizi: 'Kitchen & bathroom',
  gallery_open: 'Open photo',
  lb_close: 'Close',
  lb_prev: 'Previous photo',
  lb_next: 'Next photo',

  amenities_label: 'Amenities',
  amenities_title: 'Everything you need',
  amenities_desc: 'The apartment has been carefully equipped to ensure a comfortable and worry-free stay',
  amen_conn_title: 'Connectivity',
  amen_conn_1: 'Free dual-band WiFi (5G and 2.4G)',
  amen_conn_2: 'TV in every room',
  amen_conn_3: 'USB charging station (6 ports)',
  amen_conn_4: 'Home cinema projector',
  amen_kitchen_title: 'Kitchen',
  amen_kit_1: 'Fully equipped kitchen',
  amen_kit_2: 'Multi-program electric oven',
  amen_kit_4: 'Fridge, dishes and utensils',
  amen_climate_title: 'Climate & Comfort',
  amen_cli_1: 'Air conditioning in every room',
  amen_cli_2: 'Heating with programmable thermostat',
  amen_cli_3: 'Motorised shutters',
  amen_cli_4: 'Blackout curtain in bedroom',
  amen_parking_title: 'Parking & Access',
  amen_park_1: 'Private garage included',
  amen_park_2: 'Remote-controlled access',
  amen_park_3: 'Building lift',
  amen_park_4: 'EV charging station 200m away',
  amen_leisure_title: 'Leisure & Culture',
  amen_lei_1: 'Library with 300+ books',
  amen_lei_2: 'Home cinema with projector',
  amen_lei_3: 'Furnished panoramic terrace',
  amen_lei_4: 'Covered veranda with sea view',
  amen_safety_title: 'Safety',
  amen_saf_1: 'Smoke and CO detector',
  amen_saf_2: 'Gas detector with safety valve',
  amen_saf_3: 'Fire extinguisher on veranda',
  amen_saf_4: 'First aid kit',

  loc_label: 'Location',
  loc_title: 'In central Milazzo,<br>15 minutes from the port',
  loc_desc: 'Via Cristoforo Colombo, 7 — just steps from restaurants, bars, supermarkets, beaches and the port for the Aeolian Islands.',
  walk_title: 'On foot from the Attico',
  walk_conad: 'Conad Supermarket',
  walk_beach: 'Ponente Beach',
  walk_medical: '24/7 Medical Guard',
  walk_castle: 'Castle and Citadel',
  walk_port: 'Port for the Aeolian Islands',
  walk_min: 'min walk',
  walk_m: 'metres',
  loc_beaches: 'Beaches',
  loc_beaches_desc: 'Ponente Beach and Croce di Mare just minutes on foot',
  loc_restaurants: 'Restaurants and Bars',
  loc_restaurants_desc: 'La Campagnola, Adagio-Adagio, Macchianera — all nearby',
  map_open: 'Open in Google Maps',
  map_route: 'Get directions',
  map_title: 'Location of Attico Panoramico on Google Maps – Via Cristoforo Colombo 7, Milazzo',

  disc_label: 'Discover Milazzo',
  guide_label: 'Our travel guides',
  disc_title: 'A destination to experience',
  disc_desc: 'Milazzo is not just a departure point for the Aeolian Islands: it\'s a city rich in history, beaches and unique views, all waiting to be explored on foot from our apartment.',
  disc_castle_title: 'Castle and Citadel',
  disc_castle_desc: 'The largest fortified citadel in Sicily, over 7 hectares of history. Inside the Ancient Cathedral (1608) and the <strong>MuMa — Sea Museum</strong>. 10 minutes on foot from the apartment.',
  disc_beach_title: 'Beaches and Cape Milazzo',
  disc_beach_desc: '<strong>Ponente Beach</strong> 5 minutes on foot, Baia del Tono and the spectacular <strong>Venus Pool</strong> — a natural pool at the very tip of Cape Milazzo, an 8 km promontory in the Tyrrhenian Sea.',
  disc_eolie_title: 'Aeolian Islands',
  disc_eolie_desc: 'The port is <strong>15 minutes on foot</strong>. Hydrofoils and ferries connect all 7 islands: Lipari, Vulcano, Salina, Stromboli, Panarea, Filicudi and Alicudi. Perfect for day trips.',
  disc_food_title: 'Local cuisine',
  disc_food_desc: 'Fresh fish, arancini, Sicilian granita and Etna wines. Just steps away you\'ll find La Campagnola, Macchianera and many other typical restaurants. The pedestrian area is the heart of evening life.',
  disc_how_title: 'How to get here',
  disc_how_desc: 'From <strong>Catania (CTA)</strong>: 1h40 via A18+A20. From <strong>Palermo (PMO)</strong>: 2h15 via A20. From <strong>Messina</strong>: 35 min via A20. Milazzo railway station on the Messina–Palermo line.',
  disc_history_title: 'History and Culture',
  disc_history_desc: 'Founded by the Greeks in 716 BC, site of Rome\'s first naval victory (260 BC) and Garibaldi\'s battle (1860). The Sanctuary of San Francesco di Paola is the only one in Sicily dedicated to the saint.',
  eolie_caption: 'The seven islands, from the port of Milazzo',
  eolie_sicily: 'Sicily',
  eolie_sea: 'Tyrrhenian Sea',

  avail_label: 'Calendar',
  avail_title: 'Check availability',
  avail_desc: 'Choose your arrival and departure dates: we\'ll prepare the WhatsApp message for you, you just have to send it.',
  avail_free: 'Available',
  avail_busy: 'Booked',
  avail_mine: 'Your dates',
  avail_checkin: 'Arrival',
  avail_checkout: 'Departure',
  avail_guests: 'Guests',
  avail_night: 'night',
  avail_nights: 'nights',
  avail_pick1: 'Tap a free day on the calendar, or tap «Arrival» below',
  avail_choose: 'Choose',
  avail_pick2: 'Now choose your departure day',
  avail_ready: 'Dates chosen: send your request on WhatsApp',
  avail_conflict: 'Some nights are already booked: please try other dates.',
  avail_order: 'Departure must be after arrival.',
  avail_reset: 'Clear dates',
  avail_send: 'Send on WhatsApp',
  avail_less: 'One guest less',
  avail_more: 'One guest more',
  avail_prev: 'Previous months',
  avail_next: 'Next months',
  avail_loading: 'Loading availability…',
  avail_error: 'Calendar unavailable right now: choose your dates anyway and we\'ll confirm them on WhatsApp.',
  avail_updated: 'Updated:',
  cal_months: 'January,February,March,April,May,June,July,August,September,October,November,December',
  cal_days: 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',

  msg_generic: 'Hello! I would like some information about the Attico Panoramico in Milazzo.',
  msg_generic_dates: 'Hello! I would like some information about the Attico Panoramico in Milazzo, arriving on {da} and leaving on {a}.',
  msg_dates: 'Hello! I would like to know if the Attico Panoramico is available from {da} to {a} ({notti}) for {ospiti}. Thank you!',
  msg_guest: 'guest',
  msg_guests: 'guests',

  rev_label: 'Reviews',
  rev_title: 'How our guests rate us',
  rev_subtitle: '82 reviews on Airbnb, rated 5.0',
  rev_count: 'Based on 82 Airbnb reviews',
  rev_source: 'Ratings you can check on each site',
  rev_v_airbnb: '5.0',
  rev_v_booking: '9.8',
  rev_v_vrbo: '9.6',
  rev_n_airbnb: '82 reviews',
  rev_n_booking: '22 reviews',
  rev_n_vrbo: '5 reviews',
  rev_badge_airbnb: 'Guest favourite',
  rev_badge_booking: 'Exceptional',
  rev_badge_vrbo: 'Exceptional',
  rev_leggi: 'Read the reviews',

  faq_label: 'Frequently asked questions',
  faq_title: 'Everything you want to know',
  faq: [
    ['Where is the Attico Panoramico in Milazzo located?', 'The apartment is at Via Cristoforo Colombo 7, in the historic centre of Milazzo (ME), Sicily. It is just steps from restaurants, bars, supermarkets, beaches and the port for the Aeolian Islands.'],
    ['How many guests can the penthouse accommodate?', 'The apartment sleeps up to 8 guests. It has 3 bedrooms (two doubles and one with two single beds), a double sofa bed in the living room, 2 bathrooms, a fully equipped kitchen and a panoramic terrace.'],
    ['Is parking included?', 'Yes, the apartment includes a private garage with remote-controlled access, at no extra cost.'],
    ['What is the apartment\'s rating?', 'The Attico Panoramico is rated 5.0 out of 5 on Airbnb, with 82 guest reviews. On Booking.com it scores 9.8 out of 10 (22 reviews) and on Vrbo 9.6 out of 10 (5 reviews).'],
    ['How do I contact the owner to book?', 'Write to us on WhatsApp at +39 388 077 5449: it is the quickest way to ask about availability and book.'],
    ['What is there to see in Milazzo?', 'Milazzo offers the Castle and fortified Citadel (the largest in Sicily, over 7 hectares), Cape Milazzo with the Venus Pool, the Ponente and Baia del Tono beaches, the historic centre with its pedestrian area, the Sanctuary of San Francesco di Paola and the MuMa — Sea Museum.'],
    ['How do you reach the Aeolian Islands from Milazzo?', 'The port of Milazzo is a 15-minute walk from the apartment. Hydrofoils and ferries connect all 7 Aeolian Islands (Lipari, Vulcano, Salina, Stromboli, Panarea, Filicudi, Alicudi), ideal for day trips.'],
    ['How do you get to Milazzo?', 'From Catania Fontanarossa (CTA): 1h40 via the A18+A20 motorway. From Palermo Falcone-Borsellino (PMO): 2h15 via the A20. From Messina: 35 minutes via the A20. Milazzo also has a railway station on the Messina–Palermo line.']
  ],

  cta_label: 'Book your stay',
  cta_title: 'Ready for an<br>unforgettable experience?',
  cta_desc: 'Contact us directly for information, availability and rates: we reply on WhatsApp.',
  cta_wa: 'Write us on WhatsApp',

  footer_desc: 'Elegant holiday home in the historic centre of Milazzo, with panoramic terrace and sea view.',
  footer_links_title: 'Quick Links',
  footer_contacts_title: 'Contacts',
  footer_rights: 'All rights reserved',
  footer_guide: 'House Guide',
  bar_wa: 'WhatsApp'
},

/* ============================ DEUTSCH ============================ */
de: {
  meta_title: 'Attico Panoramico Milazzo – Ferienwohnung mit Meerblick | Sizilien',
  meta_desc: 'Ferienwohnung im historischen Zentrum von Milazzo mit Panoramaterrasse und Meerblick, Privatgarage, Heimkino und WLAN. Bis zu 8 Gäste, 82 Bewertungen mit 5 Sternen.',
  skip: 'Zum Hauptinhalt springen',
  tagline: 'Ihre Oase in Milazzo!',

  nav_apartment: 'Die Wohnung',
  nav_gallery: 'Galerie',
  nav_amenities: 'Ausstattung',
  nav_location: 'Lage',
  nav_discover: 'Milazzo entdecken',
  nav_availability: 'Verfügbarkeit',
  nav_reviews: 'Bewertungen',
  nav_faq: 'FAQ',
  nav_book: 'Buchen',
  menu_open: 'Menü öffnen',
  menu_close: 'Menü schließen',

  hero_eyebrow: 'Milazzo · Sizilien',
  hero_sub: 'Meerblick in der Altstadt von Milazzo',
  hero_desc: 'Eleganz, Komfort und atemberaubende Panoramen im Herzen von Milazzo. Private Terrasse, Garage inklusive, Heimkino – und der Fährhafen zu den Äolischen Inseln nur 15 Gehminuten entfernt.',
  hero_cta_dates: 'Termine prüfen',
  hero_cta_wa: 'Schreiben Sie uns auf WhatsApp',
  hero_rating_label: '82 Bewertungen',
  hero_rating_source: 'Airbnb',
  hero_alt: 'Die Panoramaterrasse des Attico mit Blick auf das Meer von Milazzo',
  img_alt: 'Attico Panoramico, Ferienwohnung in Milazzo, Sizilien',
  about_img_alt: 'Wohnzimmer mit Essbereich der Ferienwohnung Attico Panoramico in Milazzo',
  about_inset_alt: 'Heimkino mit Beamer in der Ferienwohnung Attico Panoramico, Milazzo',

  live_time: 'Jetzt in Milazzo',
  live_weather: 'Der Himmel',
  live_sea: 'Das Meer',
  live_sunset: 'Sonnenuntergang',
  live_sunset_tomorrow: 'Sonnenuntergang morgen',
  live_in: 'in',
  w_clear: 'Klar', w_partly: 'Leicht bewölkt', w_cloudy: 'Bewölkt', w_fog: 'Nebel',
  w_drizzle: 'Nieselregen', w_rain: 'Regen', w_snow: 'Schnee', w_storm: 'Gewitter',

  feat_guests: 'Bis zu 8 Gäste',
  feat_guests_sub: 'Unabhängige Wohnung',
  feat_sea: 'Meerblick',
  feat_sea_sub: 'Panoramaterrasse',
  feat_garage: 'Privatgarage',
  feat_garage_sub: 'Parkplatz inklusive',
  feat_cinema: 'Heimkino',
  feat_cinema_sub: 'HD-Beamer',
  feat_library: 'Bibliothek',
  feat_library_sub: 'Über 300 Bücher',
  feat_stars: '5 Sterne · 82 Bewertungen',
  feat_stars_sub: 'Auf Airbnb',

  about_label: 'Die Wohnung',
  about_title: 'Luxus und Komfort<br>im Herzen von Milazzo',
  about_desc: 'Übernachten Sie in einer eleganten, unabhängigen Penthouse-Wohnung, die höchste Entspannung und Wohlbefinden bietet. Jedes Detail wurde sorgfältig gestaltet, um Ihnen ein einzigartiges und unvergessliches Erlebnis zu bieten — nur wenige Schritte von Restaurants, Bars, Stränden und dem Hafen zu den Äolischen Inseln entfernt.',
  stat_guests: 'Max. Gäste',
  stat_rating: 'Gästebewertung',
  stat_reviews: 'Bewertungen auf Airbnb',
  stat_books: 'Bücher in der Bibliothek',

  gallery_label: 'Fotografien',
  gallery_title: 'Einblicke in die Wohnung',
  gallery_desc: 'Helle Räume, stilvolle Einrichtung und Ausblicke, die den Atem rauben',
  filter_all: 'Alle',
  filter_esterni: 'Terrasse',
  filter_soggiorno: 'Wohnbereich',
  filter_camere: 'Schlafzimmer',
  filter_servizi: 'Küche & Bad',
  gallery_open: 'Foto öffnen',
  lb_close: 'Schließen',
  lb_prev: 'Vorheriges Foto',
  lb_next: 'Nächstes Foto',

  amenities_label: 'Ausstattung',
  amenities_title: 'Alles, was Sie brauchen',
  amenities_desc: 'Die Wohnung wurde sorgfältig ausgestattet, um Ihnen einen komfortablen und sorgenfreien Aufenthalt zu garantieren',
  amen_conn_title: 'Konnektivität',
  amen_conn_1: 'Kostenloses Dual-Band-WLAN (5G und 2,4G)',
  amen_conn_2: 'TV in jedem Zimmer',
  amen_conn_3: 'USB-Ladestation (6 Anschlüsse)',
  amen_conn_4: 'Heimkino-Beamer',
  amen_kitchen_title: 'Küche',
  amen_kit_1: 'Voll ausgestattete Küche',
  amen_kit_2: 'Elektro-Backofen mit Mehrfachprogramm',
  amen_kit_4: 'Kühlschrank, Geschirr und Utensilien',
  amen_climate_title: 'Klima & Komfort',
  amen_cli_1: 'Klimaanlage in jedem Raum',
  amen_cli_2: 'Heizung mit programmierbarem Thermostat',
  amen_cli_3: 'Motorisierte Rollläden',
  amen_cli_4: 'Verdunkelungsvorhang im Schlafzimmer',
  amen_parking_title: 'Parken & Zugang',
  amen_park_1: 'Privatgarage inklusive',
  amen_park_2: 'Zugang per Fernbedienung',
  amen_park_3: 'Aufzug im Gebäude',
  amen_park_4: 'E-Auto-Ladestation 200 m entfernt',
  amen_leisure_title: 'Freizeit & Kultur',
  amen_lei_1: 'Bibliothek mit über 300 Büchern',
  amen_lei_2: 'Heimkino mit Beamer',
  amen_lei_3: 'Möblierte Panoramaterrasse',
  amen_lei_4: 'Überdachte Veranda mit Meerblick',
  amen_safety_title: 'Sicherheit',
  amen_saf_1: 'Rauch- und CO-Melder',
  amen_saf_2: 'Gasdetektor mit Sicherheitsventil',
  amen_saf_3: 'Feuerlöscher auf der Veranda',
  amen_saf_4: 'Erste-Hilfe-Set',

  loc_label: 'Lage',
  loc_title: 'Im Zentrum von Milazzo,<br>15 Minuten vom Hafen',
  loc_desc: 'Via Cristoforo Colombo, 7 — nur wenige Schritte von Restaurants, Bars, Supermärkten, Stränden und dem Hafen zu den Äolischen Inseln.',
  walk_title: 'Zu Fuß vom Attico',
  walk_conad: 'Conad Supermarkt',
  walk_beach: 'Ponente-Strand',
  walk_medical: 'Ärztlicher Bereitschaftsdienst',
  walk_castle: 'Burg und Zitadelle',
  walk_port: 'Hafen zu den Äolischen Inseln',
  walk_min: 'Gehminuten',
  walk_m: 'Meter',
  loc_beaches: 'Strände',
  loc_beaches_desc: 'Ponente-Strand und Croce di Mare nur wenige Gehminuten entfernt',
  loc_restaurants: 'Restaurants und Bars',
  loc_restaurants_desc: 'La Campagnola, Adagio-Adagio, Macchianera — alle in der Nähe',
  map_open: 'In Google Maps öffnen',
  map_route: 'Route planen',
  map_title: 'Lage des Attico Panoramico auf Google Maps – Via Cristoforo Colombo 7, Milazzo',

  disc_label: 'Milazzo entdecken',
  guide_label: 'Unsere Reiseführer',
  disc_title: 'Ein Reiseziel zum Erleben',
  disc_desc: 'Milazzo ist nicht nur ein Ausgangspunkt zu den Äolischen Inseln: Es ist eine Stadt voller Geschichte, Strände und einzigartiger Ausblicke — alles zu Fuß von unserer Wohnung aus zu erkunden.',
  disc_castle_title: 'Burg und Zitadelle',
  disc_castle_desc: 'Die größte befestigte Zitadelle Siziliens, über 7 Hektar Geschichte. Im Inneren der Alte Dom (1608) und das <strong>MuMa — Meeresmuseum</strong>. 10 Gehminuten von der Wohnung.',
  disc_beach_title: 'Strände und Kap Milazzo',
  disc_beach_desc: '<strong>Ponente-Strand</strong> 5 Gehminuten entfernt, Baia del Tono und der spektakuläre <strong>Venuspool</strong> — ein natürlicher Pool an der äußersten Spitze des Kap Milazzo, einem 8 km langen Vorgebirge im Tyrrhenischen Meer.',
  disc_eolie_title: 'Äolische Inseln',
  disc_eolie_desc: 'Der Hafen ist <strong>15 Gehminuten</strong> entfernt. Tragflügelboote und Fähren verbinden alle 7 Inseln: Lipari, Vulcano, Salina, Stromboli, Panarea, Filicudi und Alicudi. Ideal für Tagesausflüge.',
  disc_food_title: 'Lokale Gastronomie',
  disc_food_desc: 'Frischer Fisch, Arancini, sizilianische Granita und Ätna-Weine. Nur wenige Schritte entfernt finden Sie La Campagnola, Macchianera und viele andere typische Restaurants. Die Fußgängerzone ist das Herz des Abendlebens.',
  disc_how_title: 'Anreise',
  disc_how_desc: 'Von <strong>Catania (CTA)</strong>: 1 Std. 40 über A18+A20. Von <strong>Palermo (PMO)</strong>: 2 Std. 15 über A20. Von <strong>Messina</strong>: 35 Min. über A20. Bahnhof Milazzo an der Strecke Messina–Palermo.',
  disc_history_title: 'Geschichte und Kultur',
  disc_history_desc: '716 v. Chr. von den Griechen gegründet, Schauplatz des ersten Seesiegs Roms (260 v. Chr.) und der Schlacht Garibaldis (1860). Das Heiligtum San Francesco di Paola ist das einzige in Sizilien, das diesem Heiligen gewidmet ist.',
  eolie_caption: 'Die sieben Inseln, vom Hafen Milazzo aus',
  eolie_sicily: 'Sizilien',
  eolie_sea: 'Tyrrhenisches Meer',

  avail_label: 'Kalender',
  avail_title: 'Verfügbarkeit prüfen',
  avail_desc: 'Wählen Sie An- und Abreisedatum: Wir bereiten die WhatsApp-Nachricht für Sie vor, Sie müssen sie nur noch senden.',
  avail_free: 'Verfügbar',
  avail_busy: 'Gebucht',
  avail_mine: 'Ihre Termine',
  avail_checkin: 'Anreise',
  avail_checkout: 'Abreise',
  avail_guests: 'Gäste',
  avail_night: 'Nacht',
  avail_nights: 'Nächte',
  avail_pick1: 'Tippen Sie auf einen freien Tag im Kalender oder unten auf „Anreise“',
  avail_choose: 'Wählen',
  avail_pick2: 'Wählen Sie nun den Abreisetag',
  avail_ready: 'Termine gewählt: Senden Sie Ihre Anfrage per WhatsApp',
  avail_conflict: 'Einige Nächte sind bereits gebucht: Bitte wählen Sie andere Termine.',
  avail_order: 'Die Abreise muss nach der Anreise liegen.',
  avail_reset: 'Termine löschen',
  avail_send: 'Per WhatsApp senden',
  avail_less: 'Ein Gast weniger',
  avail_more: 'Ein Gast mehr',
  avail_prev: 'Vorherige Monate',
  avail_next: 'Nächste Monate',
  avail_loading: 'Verfügbarkeit wird geladen…',
  avail_error: 'Kalender derzeit nicht verfügbar: Wählen Sie trotzdem Ihre Termine, wir bestätigen sie per WhatsApp.',
  avail_updated: 'Aktualisiert:',
  cal_months: 'Januar,Februar,März,April,Mai,Juni,Juli,August,September,Oktober,November,Dezember',
  cal_days: 'Mo,Di,Mi,Do,Fr,Sa,So',

  msg_generic: 'Guten Tag! Ich hätte gerne Informationen zum Attico Panoramico in Milazzo.',
  msg_generic_dates: 'Guten Tag! Ich hätte gerne Informationen zum Attico Panoramico in Milazzo, mit Anreise am {da} und Abreise am {a}.',
  msg_dates: 'Guten Tag! Ich möchte wissen, ob das Attico Panoramico vom {da} bis {a} ({notti}) für {ospiti} verfügbar ist. Vielen Dank!',
  msg_guest: 'Gast',
  msg_guests: 'Gäste',

  rev_label: 'Bewertungen',
  rev_title: 'So bewerten uns unsere Gäste',
  rev_subtitle: '82 Bewertungen auf Airbnb, Note 5,0',
  rev_count: 'Basierend auf 82 Airbnb-Bewertungen',
  rev_source: 'Auf jedem Portal nachprüfbar',
  rev_v_airbnb: '5,0',
  rev_v_booking: '9,8',
  rev_v_vrbo: '9,6',
  rev_n_airbnb: '82 Bewertungen',
  rev_n_booking: '22 Bewertungen',
  rev_n_vrbo: '5 Bewertungen',
  rev_badge_airbnb: 'Gäste-Favorit',
  rev_badge_booking: 'Außergewöhnlich',
  rev_badge_vrbo: 'Außergewöhnlich',
  rev_leggi: 'Bewertungen lesen',

  faq_label: 'Häufige Fragen',
  faq_title: 'Alles, was Sie wissen möchten',
  faq: [
    ['Wo befindet sich das Attico Panoramico in Milazzo?', 'Die Wohnung befindet sich in der Via Cristoforo Colombo 7, im historischen Zentrum von Milazzo (ME), Sizilien. Restaurants, Bars, Supermärkte, Strände und der Hafen zu den Äolischen Inseln sind nur wenige Schritte entfernt.'],
    ['Wie viele Gäste können in der Wohnung übernachten?', 'Die Wohnung bietet Platz für bis zu 8 Gäste. Sie verfügt über 3 Schlafzimmer (zwei Doppelzimmer und eines mit zwei Einzelbetten), ein Doppelschlafsofa im Wohnzimmer, 2 Badezimmer, eine voll ausgestattete Küche und eine Panoramaterrasse.'],
    ['Ist ein Parkplatz inbegriffen?', 'Ja, die Wohnung verfügt über eine private Garage mit Zugang per Fernbedienung, ohne zusätzliche Kosten.'],
    ['Wie ist die Bewertung der Wohnung?', 'Das Attico Panoramico hat auf Airbnb eine Bewertung von 5,0 von 5 bei 82 Gästebewertungen. Auf Booking.com erreicht es 9,8 von 10 (22 Bewertungen) und auf Vrbo 9,6 von 10 (5 Bewertungen).'],
    ['Wie kontaktiere ich den Eigentümer für eine Buchung?', 'Schreiben Sie uns auf WhatsApp unter +39 388 077 5449: So erfahren Sie am schnellsten alles über Verfügbarkeit und Buchung.'],
    ['Was gibt es in Milazzo zu sehen?', 'Milazzo bietet die Burg und befestigte Zitadelle (die größte Siziliens, über 7 Hektar), das Kap Milazzo mit dem Venuspool, die Strände Ponente und Baia del Tono, die Altstadt mit Fußgängerzone, das Heiligtum San Francesco di Paola und das MuMa — Meeresmuseum.'],
    ['Wie erreicht man die Äolischen Inseln von Milazzo aus?', 'Der Hafen von Milazzo ist 15 Gehminuten von der Wohnung entfernt. Tragflügelboote und Fähren verbinden alle 7 Äolischen Inseln (Lipari, Vulcano, Salina, Stromboli, Panarea, Filicudi, Alicudi) — ideal für Tagesausflüge.'],
    ['Wie kommt man nach Milazzo?', 'Von Catania Fontanarossa (CTA): 1 Std. 40 über die A18+A20. Von Palermo Falcone-Borsellino (PMO): 2 Std. 15 über die A20. Von Messina: 35 Minuten über die A20. Milazzo hat außerdem einen Bahnhof an der Strecke Messina–Palermo.']
  ],

  cta_label: 'Ihren Aufenthalt buchen',
  cta_title: 'Bereit für ein<br>unvergessliches Erlebnis?',
  cta_desc: 'Kontaktieren Sie uns direkt für Informationen, Verfügbarkeit und Preise: Wir antworten auf WhatsApp.',
  cta_wa: 'Schreiben Sie uns auf WhatsApp',

  footer_desc: 'Elegantes Ferienhaus in der Altstadt von Milazzo, mit Panoramaterrasse und Meerblick.',
  footer_links_title: 'Schnellzugriff',
  footer_contacts_title: 'Kontakt',
  footer_rights: 'Alle Rechte vorbehalten',
  footer_guide: 'Hausführer',
  bar_wa: 'WhatsApp'
},

/* ============================ FRANÇAIS ============================ */
fr: {
  meta_title: 'Attico Panoramico Milazzo – Maison de vacances vue sur mer | Sicile',
  meta_desc: 'Maison de vacances dans le centre historique de Milazzo avec terrasse panoramique vue sur mer, garage privé, home cinéma et WiFi. Jusqu\'à 8 voyageurs, 82 avis 5 étoiles.',
  skip: 'Aller au contenu principal',
  tagline: 'Votre oasis à Milazzo !',

  nav_apartment: 'L\'Appartement',
  nav_gallery: 'Galerie',
  nav_amenities: 'Équipements',
  nav_location: 'Situation',
  nav_discover: 'Découvrir Milazzo',
  nav_availability: 'Disponibilité',
  nav_reviews: 'Avis',
  nav_faq: 'FAQ',
  nav_book: 'Réserver',
  menu_open: 'Ouvrir le menu',
  menu_close: 'Fermer le menu',

  hero_eyebrow: 'Milazzo · Sicile',
  hero_sub: 'Vue sur mer au cœur historique de Milazzo',
  hero_desc: 'Élégance, confort et panoramas à couper le souffle au cœur de Milazzo. Terrasse privée, garage inclus, home cinéma et le port des îles Éoliennes à 15 minutes à pied.',
  hero_cta_dates: 'Vérifier les dates',
  hero_cta_wa: 'Écrivez-nous sur WhatsApp',
  hero_rating_label: '82 avis',
  hero_rating_source: 'Airbnb',
  hero_alt: 'La terrasse panoramique de l\'Attico avec vue sur la mer de Milazzo',
  img_alt: 'Attico Panoramico, location de vacances à Milazzo, Sicile',
  about_img_alt: 'Séjour avec coin repas de l\'appartement de vacances Attico Panoramico à Milazzo',
  about_inset_alt: 'Home cinéma avec vidéoprojecteur à l\'Attico Panoramico, Milazzo',

  live_time: 'En ce moment à Milazzo',
  live_weather: 'Le ciel',
  live_sea: 'La mer',
  live_sunset: 'Coucher du soleil',
  live_sunset_tomorrow: 'Coucher du soleil demain',
  live_in: 'dans',
  w_clear: 'Dégagé', w_partly: 'Peu nuageux', w_cloudy: 'Nuageux', w_fog: 'Brouillard',
  w_drizzle: 'Bruine', w_rain: 'Pluie', w_snow: 'Neige', w_storm: 'Orage',

  feat_guests: 'Jusqu\'à 8 voyageurs',
  feat_guests_sub: 'Appartement indépendant',
  feat_sea: 'Vue sur Mer',
  feat_sea_sub: 'Terrasse panoramique',
  feat_garage: 'Garage privé',
  feat_garage_sub: 'Parking inclus',
  feat_cinema: 'Home Cinéma',
  feat_cinema_sub: 'Vidéoprojecteur HD',
  feat_library: 'Bibliothèque',
  feat_library_sub: 'Plus de 300 livres',
  feat_stars: '5 étoiles · 82 avis',
  feat_stars_sub: 'Sur Airbnb',

  about_label: 'L\'Appartement',
  about_title: 'Luxe et confort<br>au cœur de Milazzo',
  about_desc: 'Séjournez dans un élégant appartement penthouse indépendant offrant le summum de la détente et du bien-être. Chaque détail a été soigné pour vous offrir une expérience unique et inoubliable, à quelques pas des restaurants, bars, plages et du port vers les Îles Éoliennes.',
  stat_guests: 'Voyageurs max.',
  stat_rating: 'Note des hôtes',
  stat_reviews: 'Avis sur Airbnb',
  stat_books: 'Livres en bibliothèque',

  gallery_label: 'Photographies',
  gallery_title: 'Aperçus de l\'appartement',
  gallery_desc: 'Espaces lumineux, mobilier raffiné et vues à couper le souffle',
  filter_all: 'Toutes',
  filter_esterni: 'Terrasse',
  filter_soggiorno: 'Séjour',
  filter_camere: 'Chambres',
  filter_servizi: 'Cuisine & salle de bain',
  gallery_open: 'Ouvrir la photo',
  lb_close: 'Fermer',
  lb_prev: 'Photo précédente',
  lb_next: 'Photo suivante',

  amenities_label: 'Équipements',
  amenities_title: 'Tout ce dont vous avez besoin',
  amenities_desc: 'L\'appartement a été soigneusement équipé pour vous garantir un séjour confortable et sans souci',
  amen_conn_title: 'Connectivité',
  amen_conn_1: 'WiFi gratuit double bande (5G et 2,4G)',
  amen_conn_2: 'TV dans chaque pièce',
  amen_conn_3: 'Station de recharge USB (6 ports)',
  amen_conn_4: 'Vidéoprojecteur home cinéma',
  amen_kitchen_title: 'Cuisine',
  amen_kit_1: 'Cuisine entièrement équipée',
  amen_kit_2: 'Four électrique multi-programmes',
  amen_kit_4: 'Réfrigérateur, vaisselle et ustensiles',
  amen_climate_title: 'Climat & Confort',
  amen_cli_1: 'Climatisation dans chaque pièce',
  amen_cli_2: 'Chauffage avec thermostat programmable',
  amen_cli_3: 'Volets roulants motorisés',
  amen_cli_4: 'Rideau occultant dans la chambre',
  amen_parking_title: 'Parking & Accès',
  amen_park_1: 'Garage privé inclus',
  amen_park_2: 'Accès par télécommande',
  amen_park_3: 'Ascenseur dans l\'immeuble',
  amen_park_4: 'Borne de recharge VE à 200 m',
  amen_leisure_title: 'Loisirs & Culture',
  amen_lei_1: 'Bibliothèque de plus de 300 livres',
  amen_lei_2: 'Home cinéma avec vidéoprojecteur',
  amen_lei_3: 'Terrasse panoramique meublée',
  amen_lei_4: 'Véranda couverte avec vue mer',
  amen_safety_title: 'Sécurité',
  amen_saf_1: 'Détecteur de fumée et de CO',
  amen_saf_2: 'Détecteur de gaz avec électrovanne',
  amen_saf_3: 'Extincteur sur la véranda',
  amen_saf_4: 'Trousse de premiers secours',

  loc_label: 'Situation',
  loc_title: 'Au centre de Milazzo,<br>à 15 minutes du port',
  loc_desc: 'Via Cristoforo Colombo, 7 — à quelques pas des restaurants, bars, supermarchés, plages et du port vers les Îles Éoliennes.',
  walk_title: 'À pied depuis l\'Attico',
  walk_conad: 'Supermarché Conad',
  walk_beach: 'Plage de Ponente',
  walk_medical: 'Garde médicale 24h/24',
  walk_castle: 'Château et Citadelle',
  walk_port: 'Port vers les Îles Éoliennes',
  walk_min: 'min à pied',
  walk_m: 'mètres',
  loc_beaches: 'Plages',
  loc_beaches_desc: 'Plage de Ponente et Croce di Mare à quelques minutes à pied',
  loc_restaurants: 'Restaurants et Bars',
  loc_restaurants_desc: 'La Campagnola, Adagio-Adagio, Macchianera — tous à proximité',
  map_open: 'Ouvrir dans Google Maps',
  map_route: 'Itinéraire',
  map_title: 'Emplacement de l\'Attico Panoramico sur Google Maps – Via Cristoforo Colombo 7, Milazzo',

  disc_label: 'Découvrir Milazzo',
  guide_label: 'Nos guides de voyage',
  disc_title: 'Une destination à vivre',
  disc_desc: 'Milazzo n\'est pas seulement un point de départ vers les Îles Éoliennes : c\'est une ville riche en histoire, plages et panoramas uniques, à explorer à pied depuis notre appartement.',
  disc_castle_title: 'Château et Citadelle',
  disc_castle_desc: 'La plus grande citadelle fortifiée de Sicile, plus de 7 hectares d\'histoire. À l\'intérieur, l\'Ancienne Cathédrale (1608) et le <strong>MuMa — Musée de la Mer</strong>. À 10 minutes à pied de l\'appartement.',
  disc_beach_title: 'Plages et Cap Milazzo',
  disc_beach_desc: '<strong>Plage de Ponente</strong> à 5 minutes à pied, Baia del Tono et la spectaculaire <strong>Piscine de Vénus</strong> — une piscine naturelle à la pointe extrême du Cap Milazzo, un promontoire de 8 km dans la mer Tyrrhénienne.',
  disc_eolie_title: 'Îles Éoliennes',
  disc_eolie_desc: 'Le port est à <strong>15 minutes à pied</strong>. Hydroglisseurs et ferries relient les 7 îles : Lipari, Vulcano, Salina, Stromboli, Panarea, Filicudi et Alicudi. Idéal pour des excursions à la journée.',
  disc_food_title: 'Gastronomie locale',
  disc_food_desc: 'Poisson frais, arancini, granité sicilien et vins de l\'Etna. À quelques pas, vous trouverez La Campagnola, Macchianera et de nombreux autres restaurants typiques. La zone piétonne est le cœur de la vie nocturne.',
  disc_how_title: 'Comment arriver',
  disc_how_desc: 'Depuis <strong>Catane (CTA)</strong> : 1h40 via A18+A20. Depuis <strong>Palerme (PMO)</strong> : 2h15 via A20. Depuis <strong>Messine</strong> : 35 min via A20. Gare ferroviaire de Milazzo sur la ligne Messine–Palerme.',
  disc_history_title: 'Histoire et Culture',
  disc_history_desc: 'Fondée par les Grecs en 716 av. J.-C., théâtre de la première victoire navale de Rome (260 av. J.-C.) et de la bataille de Garibaldi (1860). Le Sanctuaire de San Francesco di Paola est le seul en Sicile dédié à ce saint.',
  eolie_caption: 'Les sept îles, depuis le port de Milazzo',
  eolie_sicily: 'Sicile',
  eolie_sea: 'Mer Tyrrhénienne',

  avail_label: 'Calendrier',
  avail_title: 'Vérifier la disponibilité',
  avail_desc: 'Choisissez vos dates d\'arrivée et de départ : nous préparons le message WhatsApp pour vous, il ne reste qu\'à l\'envoyer.',
  avail_free: 'Disponible',
  avail_busy: 'Réservé',
  avail_mine: 'Vos dates',
  avail_checkin: 'Arrivée',
  avail_checkout: 'Départ',
  avail_guests: 'Voyageurs',
  avail_night: 'nuit',
  avail_nights: 'nuits',
  avail_pick1: 'Touchez un jour libre du calendrier, ou « Arrivée » ci-dessous',
  avail_choose: 'Choisir',
  avail_pick2: 'Choisissez maintenant le jour du départ',
  avail_ready: 'Dates choisies : envoyez votre demande sur WhatsApp',
  avail_conflict: 'Certaines nuits sont déjà réservées : essayez d\'autres dates.',
  avail_order: 'Le départ doit être après l\'arrivée.',
  avail_reset: 'Effacer les dates',
  avail_send: 'Envoyer sur WhatsApp',
  avail_less: 'Un voyageur de moins',
  avail_more: 'Un voyageur de plus',
  avail_prev: 'Mois précédents',
  avail_next: 'Mois suivants',
  avail_loading: 'Chargement des disponibilités…',
  avail_error: 'Calendrier momentanément indisponible : choisissez quand même vos dates, nous vous les confirmerons sur WhatsApp.',
  avail_updated: 'Mis à jour :',
  cal_months: 'Janvier,Février,Mars,Avril,Mai,Juin,Juillet,Août,Septembre,Octobre,Novembre,Décembre',
  cal_days: 'Lun,Mar,Mer,Jeu,Ven,Sam,Dim',

  msg_generic: 'Bonjour ! J\'aimerais des informations sur l\'Attico Panoramico à Milazzo.',
  msg_generic_dates: 'Bonjour ! J\'aimerais des informations sur l\'Attico Panoramico à Milazzo, avec arrivée le {da} et départ le {a}.',
  msg_dates: 'Bonjour ! J\'aimerais savoir si l\'Attico Panoramico est disponible du {da} au {a} ({notti}) pour {ospiti}. Merci !',
  msg_guest: 'voyageur',
  msg_guests: 'voyageurs',

  rev_label: 'Avis',
  rev_title: 'Les notes de nos voyageurs',
  rev_subtitle: '82 avis sur Airbnb, note 5,0',
  rev_count: 'Basé sur 82 avis Airbnb',
  rev_source: 'Notes vérifiables sur chaque site',
  rev_v_airbnb: '5,0',
  rev_v_booking: '9,8',
  rev_v_vrbo: '9,6',
  rev_n_airbnb: '82 avis',
  rev_n_booking: '22 avis',
  rev_n_vrbo: '5 avis',
  rev_badge_airbnb: 'Coup de cœur voyageurs',
  rev_badge_booking: 'Exceptionnel',
  rev_badge_vrbo: 'Exceptionnel',
  rev_leggi: 'Lire les avis',

  faq_label: 'Questions fréquentes',
  faq_title: 'Tout ce que vous voulez savoir',
  faq: [
    ['Où se trouve l\'Attico Panoramico de Milazzo ?', 'L\'appartement se trouve Via Cristoforo Colombo 7, dans le centre historique de Milazzo (ME), en Sicile. Il est à quelques pas des restaurants, bars, supermarchés, plages et du port vers les Îles Éoliennes.'],
    ['Combien de voyageurs l\'appartement peut-il accueillir ?', 'L\'appartement peut accueillir jusqu\'à 8 voyageurs. Il dispose de 3 chambres (deux chambres doubles et une avec deux lits simples), d\'un canapé-lit double dans le séjour, d\'une cuisine équipée et d\'une terrasse panoramique.'],
    ['Le parking est-il inclus ?', 'Oui, l\'appartement comprend un garage privé avec accès par télécommande, sans frais supplémentaires.'],
    ['Quelle est la note de l\'appartement ?', 'L\'Attico Panoramico obtient 5,0 sur 5 sur Airbnb, avec 82 avis de voyageurs. Sur Booking.com, il obtient 9,8 sur 10 (22 avis) et sur Vrbo 9,6 sur 10 (5 avis).'],
    ['Comment contacter le propriétaire pour réserver ?', 'Écrivez-nous sur WhatsApp au +39 388 077 5449 : c\'est le moyen le plus rapide pour connaître les disponibilités et réserver.'],
    ['Que voir à Milazzo ?', 'Milazzo offre le Château et la Citadelle fortifiée (la plus grande de Sicile, plus de 7 hectares), le Cap Milazzo avec la Piscine de Vénus, les plages de Ponente et Baia del Tono, le centre historique avec sa zone piétonne, le Sanctuaire de San Francesco di Paola et le MuMa — Musée de la Mer.'],
    ['Comment rejoindre les Îles Éoliennes depuis Milazzo ?', 'Le port de Milazzo est à 15 minutes à pied de l\'appartement. Hydroglisseurs et ferries relient les 7 Îles Éoliennes (Lipari, Vulcano, Salina, Stromboli, Panarea, Filicudi, Alicudi), idéal pour des excursions à la journée.'],
    ['Comment arriver à Milazzo ?', 'Depuis Catane Fontanarossa (CTA) : 1h40 par l\'autoroute A18+A20. Depuis Palerme Falcone-Borsellino (PMO) : 2h15 par l\'A20. Depuis Messine : 35 minutes par l\'A20. Milazzo dispose également d\'une gare sur la ligne Messine–Palerme.']
  ],

  cta_label: 'Réservez votre séjour',
  cta_title: 'Prêt pour une<br>expérience inoubliable ?',
  cta_desc: 'Contactez-nous directement pour informations, disponibilités et tarifs : nous répondons sur WhatsApp.',
  cta_wa: 'Écrivez-nous sur WhatsApp',

  footer_desc: 'Élégante maison de vacances dans le centre historique de Milazzo, avec terrasse panoramique et vue sur la mer.',
  footer_links_title: 'Liens rapides',
  footer_contacts_title: 'Contacts',
  footer_rights: 'Tous droits réservés',
  footer_guide: 'Guide de la maison',
  bar_wa: 'WhatsApp'
}
};
